apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-gateway-node-port
  labels:
    app: gateway
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: gateway
  type: NodePort